#!/bin/sh
options="--timecolor=ffffffff --datecolor=ffffffff \
	   --verifcolor=00000000 --wrongcolor=ff0000ff \
       	   --ringcolor=ffffff3e --linecolor=ffffff00 \
       	   --keyhlcolor=30ff3080 --ringvercolor=00000000 \
	   --insidecolor=ffffff1c --insidevercolor=0000001c \ 
       	   --insidewrongcolor=0000001c -k "
if [ "$1" == "startup" ]; then
	options+="-i /home/james/pictures/i3lock.jpg"
elif [ "$1" == "fork" ]; then
	options+="-n -B -"
else
	options+="-B -"
fi

i3lock $options
