#!/bin/sh
options="--textcolor=ffffff00 --insidecolor=ffffff1c \
       	   --ringcolor=ffffff3e --linecolor=ffffff00 \
       	   --keyhlcolor=30ff3080 --ringvercolor=00000000 \
       	   --insidevercolor=0000001c --ringwrongcolor=00000055 \
       	   --insidewrongcolor=0000001c -k "
if [ "$1" == "startup" ]; then
	options+="-i /home/james/pictures/i3lock.png"
elif [ "$1" == "fork" ]; then
	options+="-n -B -"
else
	options+="-B -"
fi

i3lock $options
